[tool.streamlit]
pythonVersion = "3.11"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jotform-result"
version = "1.0.0"
requires-python = ">=3.9,<3.13"
